from langfuse import observe
from elevenlabs.client import ElevenLabs
import os

@observe(as_type="tool")
def convert_script_to_audio(script: str) -> str:
    """
    Converts the generated podcast script to audio using ElevenLabs.

    Args:
        script: The text script generated by Gemini.

    Returns:
        A URL or file path to the generated audio (Podcast), or an error message.
    """

    elevenlabs = ElevenLabs(api_key=os.getenv("ELEVENLABS_API_KEY"))

    audio = elevenlabs.text_to_speech.convert(
        text=script,
        voice_id="JBFqnCBsd6RMkjVDRZzb",
        model_id="eleven_multilingual_v2",
        output_format="mp3_44100_128",
    )

    return audio


