import base64
import os
from langfuse import observe
from elevenlabs.client import ElevenLabs

@observe(as_type="tool")
def convert_script_to_audio(script: str) -> str:
    """
    Converts the generated podcast script to audio using ElevenLabs
    and returns a playable Data URI (Base64).

    Args:
        script: The text script generated by Gemini.

    Returns:
        str: A Data URI string (data:audio/mpeg;base64,...) ready for the frontend.
    """
    elevenlabs = ElevenLabs(api_key=os.getenv("ELEVENLABS_API_KEY"))

    # 1. Request Audio Stream from ElevenLabs
    # This returns a generator yielding chunks of bytes
    audio_generator = elevenlabs.text_to_speech.convert(
        text=script,
        voice_id="q0IMILNRPxOgtBTS4taI",
        model_id="eleven_multilingual_v2",
        output_format="mp3_44100_128",
    )

    # 2. Consume the Generator
    # We join all chunks into a single bytes object in memory
    audio_bytes = b"".join(audio_generator)

    # 3. Encode to Base64
    audio_base64 = base64.b64encode(audio_bytes).decode('utf-8')

    # 4. Create Data URI
    # This string can be put directly into <audio src="..."> in React
    audio_data_uri = f"data:audio/mpeg;base64,{audio_base64}"

    return audio_data_uri